name: "Test"

on:
  push:
    branches:
      - develop

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    environment:
      name: ubuntu
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Ruff
      run: uv pip install ruff

    - name: Run Ruff
      run: ruff check .

    - name: Build
      run: uv build
    # Check that basic features work and we didn't miss to include crucial files
    - name: Unit test (wheel)
      run: uv run --isolated --no-project --with dist/*.whl tests/run_test.py
    - name: Unit test (source distribution)
      run: uv run --isolated --no-project --with dist/*.tar.gz tests/run_test.py